query ($first: Int!, $skip: Int!) {
    votes (
      first: $first,
      skip: $skip,
      orderBy: "created",
      orderDirection: asc
    ) 
    {
      id
      ipfs
      voter
      created
      space {
        id
      }
      proposal {
        id
      }
      choice
      metadata
      reason
      app
      vp
      vp_by_strategy
      vp_state
    }
  }